	DE2_115_SD_CARD_NIOS u0 (
		.altpll_areset_conduit_export                                    (<connected-to-altpll_areset_conduit_export>),                                    //               altpll_areset_conduit.export
		.altpll_c1_clk                                                   (<connected-to-altpll_c1_clk>),                                                   //                           altpll_c1.clk
		.altpll_c3_clk                                                   (<connected-to-altpll_c3_clk>),                                                   //                           altpll_c3.clk
		.altpll_locked_conduit_export                                    (<connected-to-altpll_locked_conduit_export>),                                    //               altpll_locked_conduit.export
		.altpll_phasedone_conduit_export                                 (<connected-to-altpll_phasedone_conduit_export>),                                 //            altpll_phasedone_conduit.export
		.c0_out_clk_clk                                                  (<connected-to-c0_out_clk_clk>),                                                  //                          c0_out_clk.clk
		.c2_out_clk_clk                                                  (<connected-to-c2_out_clk_clk>),                                                  //                          c2_out_clk.clk
		.clk_50_clk_in_clk                                               (<connected-to-clk_50_clk_in_clk>),                                               //                       clk_50_clk_in.clk
		.epp_i2c_scl_external_connection_export                          (<connected-to-epp_i2c_scl_external_connection_export>),                          //     epp_i2c_scl_external_connection.export
		.epp_i2c_sda_external_connection_export                          (<connected-to-epp_i2c_sda_external_connection_export>),                          //     epp_i2c_sda_external_connection.export
		.i2c_scl_external_connection_export                              (<connected-to-i2c_scl_external_connection_export>),                              //         i2c_scl_external_connection.export
		.i2c_sda_external_connection_export                              (<connected-to-i2c_sda_external_connection_export>),                              //         i2c_sda_external_connection.export
		.ir_external_connection_export                                   (<connected-to-ir_external_connection_export>),                                   //              ir_external_connection.export
		.key_external_connection_export                                  (<connected-to-key_external_connection_export>),                                  //             key_external_connection.export
		.lcd_external_RS                                                 (<connected-to-lcd_external_RS>),                                                 //                        lcd_external.RS
		.lcd_external_RW                                                 (<connected-to-lcd_external_RW>),                                                 //                                    .RW
		.lcd_external_data                                               (<connected-to-lcd_external_data>),                                               //                                    .data
		.lcd_external_E                                                  (<connected-to-lcd_external_E>),                                                  //                                    .E
		.ledg_external_connection_export                                 (<connected-to-ledg_external_connection_export>),                                 //            ledg_external_connection.export
		.ledr_external_connection_export                                 (<connected-to-ledr_external_connection_export>),                                 //            ledr_external_connection.export
		.reset_reset_n                                                   (<connected-to-reset_reset_n>),                                                   //                               reset.reset_n
		.rs232_external_connection_rxd                                   (<connected-to-rs232_external_connection_rxd>),                                   //           rs232_external_connection.rxd
		.rs232_external_connection_txd                                   (<connected-to-rs232_external_connection_txd>),                                   //                                    .txd
		.rs232_external_connection_cts_n                                 (<connected-to-rs232_external_connection_cts_n>),                                 //                                    .cts_n
		.rs232_external_connection_rts_n                                 (<connected-to-rs232_external_connection_rts_n>),                                 //                                    .rts_n
		.sd_clk_external_connection_export                               (<connected-to-sd_clk_external_connection_export>),                               //          sd_clk_external_connection.export
		.sd_cmd_external_connection_export                               (<connected-to-sd_cmd_external_connection_export>),                               //          sd_cmd_external_connection.export
		.sd_dat_external_connection_export                               (<connected-to-sd_dat_external_connection_export>),                               //          sd_dat_external_connection.export
		.sd_wp_n_external_connection_export                              (<connected-to-sd_wp_n_external_connection_export>),                              //         sd_wp_n_external_connection.export
		.seg7_conduit_end_export                                         (<connected-to-seg7_conduit_end_export>),                                         //                    seg7_conduit_end.export
		.sma_in_external_connection_export                               (<connected-to-sma_in_external_connection_export>),                               //          sma_in_external_connection.export
		.sma_out_external_connection_export                              (<connected-to-sma_out_external_connection_export>),                              //         sma_out_external_connection.export
		.sw_external_connection_export                                   (<connected-to-sw_external_connection_export>),                                   //              sw_external_connection.export
		.to_hw_port_export                                               (<connected-to-to_hw_port_export>),                                               //                          to_hw_port.export
		.to_hw_sig_export                                                (<connected-to-to_hw_sig_export>),                                                //                           to_hw_sig.export
		.to_sw_sig_export                                                (<connected-to-to_sw_sig_export>),                                                //                           to_sw_sig.export
		.tri_state_bridge_flash_bridge_0_out_address_to_the_cfi_flash    (<connected-to-tri_state_bridge_flash_bridge_0_out_address_to_the_cfi_flash>),    // tri_state_bridge_flash_bridge_0_out.address_to_the_cfi_flash
		.tri_state_bridge_flash_bridge_0_out_tri_state_bridge_flash_data (<connected-to-tri_state_bridge_flash_bridge_0_out_tri_state_bridge_flash_data>), //                                    .tri_state_bridge_flash_data
		.tri_state_bridge_flash_bridge_0_out_write_n_to_the_cfi_flash    (<connected-to-tri_state_bridge_flash_bridge_0_out_write_n_to_the_cfi_flash>),    //                                    .write_n_to_the_cfi_flash
		.tri_state_bridge_flash_bridge_0_out_select_n_to_the_cfi_flash   (<connected-to-tri_state_bridge_flash_bridge_0_out_select_n_to_the_cfi_flash>),   //                                    .select_n_to_the_cfi_flash
		.tri_state_bridge_flash_bridge_0_out_read_n_to_the_cfi_flash     (<connected-to-tri_state_bridge_flash_bridge_0_out_read_n_to_the_cfi_flash>)      //                                    .read_n_to_the_cfi_flash
	);

